export const ADD_CONSTRUCTOR_ITEM: "ADD_CONSTRUCTOR_ITEM" =
  "ADD_CONSTRUCTOR_ITEM";
export const REMOVE_CONSTRUCTOR_ITEM: "REMOVE_CONSTRUCTOR_ITEM" =
  "REMOVE_CONSTRUCTOR_ITEM";
export const MOVE_CONSTRUCTOR_ITEM: "MOVE_CONSTRUCTOR_ITEM" =
  "MOVE_CONSTRUCTOR_ITEM";
export const UPDATE_CONSTRUCTOR_BUN: "UPDATE_INGREDIENTS_DETAIL" =
  "UPDATE_INGREDIENTS_DETAIL";
export const RESET_CONSTRUCTOR: "RESET_CONSTRUCTOR" = "RESET_CONSTRUCTOR";