export const FEED_USER_CONNECTION_SUCCESS: "FEED_USER_CONNECTION_SUCCESS" =
  "FEED_USER_CONNECTION_SUCCESS";
export const FEED_USER_CONNECTION_ERROR: "FEED_USER_CONNECTION_ERROR" =
  "FEED_USER_CONNECTION_ERROR";
export const FEED_USER_CONNECTION_CLOSED: "FEED_USER_CONNECTION_CLOSED" =
  "FEED_USER_CONNECTION_CLOSED";
export const FEED_USER_GET_MESSAGE: "FEED_USER_GET_MESSAGE" =
  "FEED_USER_GET_MESSAGE";
export const FEED_USER_SEND_MESSAGE: "FEED_USER_SEND_MESSAGE" =
  "FEED_USER_SEND_MESSAGE";
