export const FEED_CONNECTION_SUCCESS: "FEED_CONNECTION_SUCCESS" =
  "FEED_CONNECTION_SUCCESS";
export const FEED_CONNECTION_ERROR: "FEED_CONNECTION_ERROR" =
  "FEED_CONNECTION_ERROR";
export const FEED_CONNECTION_CLOSED: "FEED_CONNECTION_CLOSED" =
  "FEED_CONNECTION_CLOSED";
export const FEED_GET_MESSAGE: "FEED_GET_MESSAGE" = "FEED_GET_MESSAGE";
export const FEED_SEND_MESSAGE: "FEED_SEND_MESSAGE" = "FEED_SEND_MESSAGE";
export const FEED_SINGLE_ORDER: "FEED_SINGLE_ORDER" = "FEED_SINGLE_ORDER";
