export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
  "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" =
  "GET_INGREDIENTS_FAILED";
export const ICREMENT_INGREDIENT_COUNT: "ICREMENT_INGREDIENT_COUNT" =
  "ICREMENT_INGREDIENT_COUNT";
export const DECREMENT_INGREDIENT_COUNT: "DECREMENT_INGREDIENT_COUNT" =
  "DECREMENT_INGREDIENT_COUNT";
export const UPDATE_INGREDIENT_COUNT_BUN: "UPDATE_INGREDIENT_COUNT_BUN" =
  "UPDATE_INGREDIENT_COUNT_BUN";
export const RESET_INGREDIENTS_COUNT: "RESET_INGREDIENTS_COUNT" =
  "RESET_INGREDIENTS_COUNT";
export const UPDATE_CURRENT_TAB: "UPDATE_CURRENT_TAB" = "UPDATE_CURRENT_TAB";
