export const GET_LOGIN_REQUEST: "GET_LOGIN_REQUEST" = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS" = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILED: "GET_LOGIN_FAILED" = "GET_LOGIN_FAILED";

export const GET_REGISTER_REQUEST: "GET_REGISTER_REQUEST" =
  "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS: "GET_REGISTER_SUCCESS" =
  "GET_REGISTER_SUCCESS";
export const GET_REGISTER_FAILED: "GET_REGISTER_FAILED" = "GET_REGISTER_FAILED";

export const GET_LOGOUT_REQUEST: "GET_LOGOUT_REQUEST" = "GET_LOGOUT_REQUEST";
export const GET_LOGOUT_SUCCESS: "GET_LOGOUT_SUCCESS" = "GET_LOGOUT_SUCCESS";
export const GET_LOGOUT_FAILED: "GET_LOGOUT_FAILED" = "GET_LOGOUT_FAILED";

export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";

export const USER_LOGOUT: "USER_LOGOUT" = "USER_LOGOUT";
export const USER_UPDATE: "USER_UPDATE" = "USER_UPDATE";
export const USER_FORGOT_PASSWORD: "USER_FORGOT_PASSWORD" =
  "USER_FORGOT_PASSWORD";
export const USER_FORGOT_PASSWORD_RESET: "USER_FORGOT_PASSWORD_RESET" =
  "USER_FORGOT_PASSWORD_RESET";
export const USER_PASSWORD_RESET: "USER_FORGOT_RESET" = "USER_FORGOT_RESET";
export const USER_DISABLE_REDDIRECT_RESET_PASSWORD =
  "USER_DISABLE_REDDIRECT_RESET_PASSWORD";