export const WS_CONNECT: "WS_CONNECT" = "WS_CONNECT";
export const WS_PROTECTED_CONNECT: "WS_PROTECTED_CONNECT" =
  "WS_PROTECTED_CONNECT";
export const WS_DISCONNECT: "WS_DISCONNECT" = "WS_DISCONNECT";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";
export const WS_SEND_MESSAGE: "WS_SEND_MESSAGE" = "WS_SEND_MESSAGE";
export const GET_SINGLE_ORDER: "GET_SINGLE_ORDER" = "GET_SINGLE_ORDER";
